export const GET_ALL_INGREDIENTS_PENDING = 'GET_ALL_INGREDIENTS_PENDING';
export const GET_ALL_INGREDIENTS_FULFILLED = 'GET_ALL_INGREDIENTS_FULFILLED';
export const GET_ALL_INGREDIENTS_ERROR = 'GET_ALL_INGREDIENTS_ERROR';